# Generated by Django 5.2.8 on 2025-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0002_album_deleted_at_album_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="password",
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("register", "Registration"),
                    ("album_create", "Album Creation"),
                    ("album_edit", "Album Edit"),
                    ("album_view", "Album View"),
                    ("album_delete", "Album Delete"),
                    ("media_upload", "Media Upload"),
                    ("media_view", "Media View"),
                    ("password_view", "Password View Attempt"),
                    ("password_edit", "Password Edit Attempt"),
                ],
                max_length=20,
            ),
        ),
    ]
