# Generated by Django 5.2.8 on 2025-11-14 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0003_remove_album_password_alter_activitylog_action"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="albums_acti_content_75e037_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["album"], name="albums_acti_album_i_2ecb02_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["media_file"], name="albums_acti_media_f_edf9e8_idx"
            ),
        ),
    ]
