# Generated by Django 5.2.8 on 2025-11-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0004_activitylog_content_type_activitylog_object_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="content_url",
            field=models.URLField(
                blank=True, help_text="URL на контент (альбом или файл)", null=True
            ),
        ),
    ]
